sonar.organization=u826318
sonar.projectKey=u826318_sopra-fs26-group-09-client

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/.history/**,coverage/**,**/*.test.ts,**/*.test.tsx,jest.config.js,jest.setup.ts
sonar.tests=app
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
